name: google_drive_client
description: A Handful Google Drive Client For Dart
version: 1.0.3
homepage: https://github.com/hokamc/google_drive_client

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: ^3.0.10
  path_provider: ^1.6.24
  path: ^1.7.0
  mime_type: ^0.3.2
